name: DataSurface Model Validator

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: DataSurface validator
      uses: billynewport/datasurface-validator@main
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}      
          base_repository: ${{ github.repository }}
          head_repository: ${{ github.event.pull_request.head.repo.full_name }}
          head_branch: ${{ github.event.pull_request.head.ref }}
